apiVersion: apps/v1
kind: Deployment
metadata:
  name: week9-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: week9-app
  template:
    metadata:
      labels:
        app: week9-app
    spec:
      containers:
        - name: week9-app
          image: DOCKERHUB_USERNAME/week9-app:BUILD_NUMBER
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
